version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   steps:
      - run:
          command: |
           git clone https://github.com/Dustxyz/kernel_xiaomi_ysl --single-branch -b rebase --depth=1 ysl
           cd ysl
           wget https://raw.githubusercontent.com/Dustxyz/personal_scripts/master/build.sh
           bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
